### PR TITLE
Add back-to-top button

### PR DESCRIPTION
**Pull request by JakeSCahill**
Preview: https://deploy-preview-206--docs-ui.netlify.app/#fin

### CODE REVIEW

**Comment by Deflaimun** [comment]
Not sure if it's working. When I click the button the url changes to https://deploy-preview-206--docs-ui.netlify.app/#, new wide scroll appears, and there's some movement, but I get back to the bottom.
image

**Comment by Deflaimun** [comment]
I think this is clashing with the announcement bar. That's why the behavior is happening. Otherwise it works

**Comment by JakeSCahill** [comment]
@Deflaimun do you have a video of this behavior? I'm not seeing it in Chrome on macos

**Comment by Deflaimun** [comment]
Animation

**Comment by Deflaimun** [comment]
This happened when I scrolled back all the way to the bottom. So I think both the script for "back to top" and the "subscribe email" are interacting and not letting the user scroll to the top.

**Review by Deflaimun — APPROVED** [review]
Seems fixed! 🚀

**Pull request merged**
